import Head from "next/head";
import AllUsers from "../components/AllUsers";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h3>AWS Date fetch</h3>
        <AllUsers />
      </div>
    </div>
  );
}
